my_exam/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy
from my_exam import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('login/', views.login_view, name='login'),
    path('register/', views.register_view, name='register'),
    path('logout/', auth_views.LogoutView.as_view(next_page=reverse_lazy('home')), name='logout'),
    path('profile/', views.profile_view, name='profile'),
    path('iphone/', views.iphone_view, name='iphone'),
    path('add_to_cart/', views.add_to_cart, name='add_to_cart'),
    path('confirm_order/', views.confirm_order, name='confirm_order'),
    path('get_cart_count/', views.get_cart_count, name='get_cart_count'),
    path('remove_from_cart/<int:item_id>/', views.remove_from_cart, name='remove_from_cart'),
]

my_exam/models.py
from django.contrib.auth.base_user import BaseUserManager
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.validators import RegexValidator


class CustomUserManager(BaseUserManager):
    def create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError('The Email field must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self.create_user(email, password, **extra_fields)

class User(AbstractUser):
    age = models.IntegerField(null=True, blank=True)
    email = models.EmailField(unique=True)
    mobile = models.CharField(max_length=15, validators=[RegexValidator(r'^\+?1?\d{9,15}$', message="Мобільний номер телефону повинен бути в форматі: '999999999'. Довжина не більше 15 символів.")])
    address = models.CharField(max_length=255, null=True, blank=True)
    username = None
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['mobile']

    objects = CustomUserManager()

    def __str__(self):
        return self.email



class Iphone(models.Model):
    name = models.CharField(max_length=100)
    color = models.CharField(max_length=50)
    memory = models.CharField(max_length=50)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    image_url = models.URLField()

    def __str__(self):
        return self.name


class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    items = models.ManyToManyField(Iphone, through='CartItem')
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Cart {self.id}"

class CartItem(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    item = models.ForeignKey(Iphone, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)
    total_price = models.DecimalField(max_digits=10, decimal_places=2, default=0)

    def __str__(self):
        return f"CartItem {self.item.name} in Cart {self.cart.id}"

my_exam/forms.py
from django import forms
from .models import User, Iphone
from django.core.validators import RegexValidator
import re


class LoginForm(forms.Form):
    mobile_or_email = forms.CharField(label='Phone або Email')
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput)

    def clean_mobile_or_email(self):
        data = self.cleaned_data['mobile_or_email']
        if re.match(r'^[0-9]+$', data):
            return data
        elif re.match(r'\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b', data):
            return data
        else:
            raise forms.ValidationError('Phone або Email неправильного формату')

class RegistrationForm(forms.ModelForm):
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput)
    confirm_password = forms.CharField(label='Підтвердіть пароль', widget=forms.PasswordInput)
    mobile = forms.CharField(label='Mobile', max_length=15, validators=[RegexValidator(r'^\+?1?\d{9,15}$', message="Мобільний номер телефону повинен бути в форматі: '+999999999'. Довжина не більше 15 символів.")])

    class Meta:
        model = User
        fields = ('first_name', 'age', 'email', 'password', 'confirm_password', 'mobile', 'address')


    def clean_mobile(self):
        mobile = self.cleaned_data.get('mobile')
        return mobile

    def clean_confirm_password(self):
        password = self.cleaned_data.get('password')
        confirm_password = self.cleaned_data.get('confirm_password')
        if password and confirm_password and password != confirm_password:
            raise forms.ValidationError('Паролі не співпадають.')
        return confirm_password

    def save(self, commit=True):
        password = self.cleaned_data['password']
        confirm_password = self.cleaned_data['confirm_password']
        if password != confirm_password:
            raise ValueError("Паролі не співпадають")
        user = super().save(commit=False)
        user.set_password(password)
        if commit:
            user.save()
        return user


class ProfileForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email']


class IphoneForm(forms.ModelForm):
    class Meta:
        model = Iphone
        fields = ['name', 'color', 'memory', 'price', 'image_url']

templates/confirm_order.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'css/confirm_order.css' %}">
    <script src="https://kit.fontawesome.com/8b70202f53.js" crossorigin="anonymous"></script>
    <script src="{% static 'script/confirm_order.js' %}"></script>
    <title>Магазин Apple техніки</title>
</head>
<body>
<header>
    <div class="left-content">
        <a href="{% url 'home' %}">
            <img src="{% static 'images/apple_logo.png' %}" alt="Apple Logo">
        </a>
        <div class="dropdown" onmouseover="showiPhoneModels()" onmouseleave="hideiPhoneModels()">
            <a href="{% url 'iphone' %}">
                <button>
                    <i class="fas fa-mobile-alt"></i> iPhone
                </button>
            </a>
        </div>
    </div>
    <div class="right-content">
        {% if user.is_authenticated %}
            <a href="{% url 'profile' %}">
                <button><i class="fas fa-user"></i> {{ user.first_name }}</button>
            </a>
            <a href="{% url 'confirm_order' %}">
                <button><i class="fas fa-shopping-basket"></i><span class="get_cart_count"></span></button>
            </a>
            <form action="{% url 'logout' %}" method="post">
                {% csrf_token %}
                <button type="submit">Вийти</button>
            </form>
        {% else %}
            <a href="{% url 'login' %}">Log in</a>
        {% endif %}
    </div>
</header>
<main>
    <h1>Корзина</h1>
    <table>
        <thead>
        <tr>
            <th>Назва товару</th>
            <th>Колір</th>
            <th>Ціна</th>
            <th>Кількість</th>
            <th>Сума</th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        {% for item in cart_items %}
            <tr>
                <td>{{ item.item.name }}</td>
                <td>{{ item.item.color }}</td>
                <td>${{ item.item.price }}</td>
                <td>{{ item.quantity }}</td>
                <td>${{ item.total_price }}</td>
                <td>
                    <button onclick="removeItem({{ item.id }})"><i class="fas fa-trash-alt"></i></button>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <div>
        <p>Загальна сума: ${{ total_price }}</p>
        <a href="{% url 'confirm_order' %}">Підтвердити замовлення</a>
    </div>
</main>

<footer>
    <div class="contact-info">
        <h3>Контактна інформація:</h3>
        <p>+380 99 444 45 67</p>
        <p>exam@mail.com</p>
    </div>
</footer>
</body>
</html>

templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'css/home.css' %}">
    <script src="{% static 'script/home.js' %}"></script>
    <script src="https://kit.fontawesome.com/8b70202f53.js" crossorigin="anonymous"></script>
    <title>Магазин Apple техніки</title>
</head>
<body>
<header>
    <div class="left-content">
        <a href="{% url 'home' %}">
            <img src="{% static 'images/apple_logo.png' %}" alt="Apple Logo">
        </a>
        <div class="dropdown" onmouseover="showiPhoneModels()" onmouseleave="hideiPhoneModels()">
            <a href="{% url 'iphone' %}">
                <button>
                    <i class="fas fa-mobile-alt"></i> iPhone
                </button>
            </a>
        </div>
    </div>
    <div class="right-content">
        {% if user.is_authenticated %}
            <a href="{% url 'profile' %}">
                <button><i class="fas fa-user"></i> {{ user.first_name }}</button>
            </a>
            <a href="{% url 'confirm_order' %}">
                <button><i class="fas fa-shopping-basket"></i><span class="get_cart_count"></span></button>
            </a>
            <form action="{% url 'logout' %}" method="post">
                {% csrf_token %}
                <button type="submit">Вийти</button>
            </form>
        {% else %}
            <a href="{% url 'login' %}">Вхід</a>
        {% endif %}
    </div>
</header>
<main>
    <h1>Ласкаво просимо до магазину Apple техніки</h1>
</main>
<footer>
    <div class="contact-info">
        <h3>Контактна інформація:</h3>
        <p>+380 99 444 45 67</p>
        <p>exam@mail.com</p>
    </div>
</footer>
</body>
</html>

templates/iphone.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="csrf-token" content="{{ csrf_token }}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/iphone.css' %}">
    <script src="{% static 'script/iphone.js' %}"></script>
    <script src="https://kit.fontawesome.com/8b70202f53.js" crossorigin="anonymous"></script>
    <title>Iphone</title>
</head>
<body>
<header>
    <div class="left-content">
        <a href="{% url 'home' %}">
            <img src="{% static 'images/apple_logo.png' %}" alt="Apple Logo">
        </a>
        <div class="dropdown" onmouseover="showiPhoneModels()" onmouseleave="hideiPhoneModels()">
            <a href="{% url 'iphone' %}">
                <button>
                    <i class="fas fa-mobile-alt"></i> iPhone
                </button>
            </a>
        </div>
    </div>
    <div class="right-content">
        {% if user.is_authenticated %}
            <a href="{% url 'profile' %}">
                <button><i class="fas fa-user"></i> {{ user.first_name }}</button>
            </a>
            <a href="{% url 'confirm_order' %}">
                <button><i class="fas fa-shopping-basket"></i><span class="get_cart_count"></span></button>
            </a>
            <form action="{% url 'logout' %}" method="post">
                {% csrf_token %}
                <button type="submit">Вийти</button>
            </form>
        {% else %}
            <a href="{% url 'login' %}">Вхід</a>
        {% endif %}
    </div>
</header>
<main>
    <div class="iphone-list">
        <div class="iphone-row">
            {% for iphone in page_obj %}
                <div class="iphone-item">
                    <img src="{{ iphone.image_url }}" alt="{{ iphone.name }}">
                    <h4>{{ iphone.name }}</h4>
                    <p>Ціна: ${{ iphone.price }}</p>
                    <p>Колір: {{ iphone.color }}</p>
                    <p>Об'єм пам'яті: {{ iphone.memory }}</p>
                    <form method="post" action="{% url 'add_to_cart' %}">
                        {% csrf_token %}
                        <input type="hidden" name="iphone_id" value="{{ iphone.id }}">
                        <button type="button" onclick="add_to_cart(this.getAttribute('data-iphone-id'))"
                                data-iphone-id="{{ iphone.id }}">Додати до корзини
                        </button>

                    </form>
                </div>
                {% if forloop.counter|divisibleby:4 and not forloop.last %}
                    </div>
                    <div class="iphone-row">
                {% endif %}
            {% endfor %}
            </div>
    </div>
    {% if page_obj.has_other_pages %}
        <div class="pagination">
            <span class="current">Сторінка {{ page_obj.number }} з {{ page_obj.paginator.num_pages }}</span>
            {% if page_obj.has_previous %}
                <a href="?page=1">Перша</a>
                <a href="?page={{ page_obj.previous_page_number }}">Попередня</a>
            {% endif %}

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">Наступна</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">Остання</a>
            {% endif %}
        </div>
    {% endif %}
</main>
<footer>
    <div class="contact-info">
        <h3>Контактна інформація:</h3>
        <p>+380 99 444 45 67</p>
        <p>exam@mail.com</p>
    </div>
</footer>
</body>
</html>

templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}">
</head>
<body>
<header>
    <div class="left-content">
        <a href="{% url 'home' %}">
            <img src="{% static 'images/apple_logo.png' %}" alt="Apple Logo">
        </a>
        <div class="dropdown" onmouseover="showiPhoneModels()" onmouseleave="hideiPhoneModels()">
            <a href="{% url 'iphone' %}">
                <button>
                    <i class="fas fa-mobile-alt"></i> iPhone
                </button>
            </a>
        </div>
    </div>
    <div class="right-content">
        {% if user.is_authenticated %}
            <a href="{% url 'profile' %}">
                <button><i class="fas fa-user"></i> {{ user.first_name }}</button>
            </a>
            <a href="{% url 'confirm_order' %}">
                <button><i class="fas fa-shopping-basket"></i><span class="get_cart_count"></span></button>
            </a>
            <form action="{% url 'logout' %}" method="post">
                {% csrf_token %}
                <button type="submit">Вийти</button>
            </form>
        {% else %}
            <a href="{% url 'login' %}">Вхід</a>
        {% endif %}
    </div>
</header>
<main>
    <div class="container">
        <h2>Авторизація</h2>

        {% if form.errors %}
            <div class="alert alert-danger">
                {% for field, errors in form.errors.items %}
                    {% for error in errors %}
                        <strong>{{ field|title }}</strong>: {{ error }}
                    {% endfor %}
                {% endfor %}
            </div>
        {% endif %}

        <form method="post">
            {% csrf_token %}
            <div>
                <label for="id_mobile_or_email" id="mobile_or_email_label"></label> <br>
                <input type="text" id="id_mobile_or_email" name="mobile_or_email" placeholder="Phone або Email"
                       onfocus="onInputFocus('id_mobile_or_email', 'mobile_or_email_label', 'Логін або Email');"
                       onblur="onInputBlur('id_mobile_or_email', 'mobile_or_email_label', 'Логін або Email');"> <br>
            </div>
            <div>
                <label for="id_password" id="password_label"></label> <br>
                <input type="password" id="id_password" name="password" placeholder="Password"
                       onfocus="onInputFocus('id_password', 'password_label', 'Пароль');"
                       onblur="onInputBlur('id_password', 'password_label', 'Пароль');"> <br>
            </div>
            <button type="submit">Вхід</button>
        </form>
    </div>

    <div class="register-link">
        <a href="{% url 'register' %}">Зареєструватися</a>
    </div>
</main>
<footer>
    <div class="contact-info">
        <h3>Контактна інформація:</h3>
        <p>+380 99 444 45 67</p>
        <p>exam@mail.com</p>
    </div>
</footer>
</body>
</html>

templates/profile.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://kit.fontawesome.com/8b70202f53.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'css/profile.css' %}">
    <script src="{% static 'script/profile.js' %}"></script>
    <title>Мій кабінет</title>
</head>
<body>

<header>
    <div class="left-content">
        <a href="{% url 'home' %}">
            <img src="{% static 'images/apple_logo.png' %}" alt="Apple Logo">
        </a>
        <a href="{% url 'iphone' %}">
            <button>
                <i class="fas fa-mobile-alt"></i> iPhone
            </button>
        </a>
    </div>
    <div class="right-content">
        {% if request.user.is_authenticated %}
            <a href="{% url 'profile' %}">
                <button><i class="fas fa-user"></i> {{ request.user.first_name }}</button>
            </a>
            <a href="{% url 'confirm_order' %}">
                <button><i class="fas fa-shopping-basket"></i><span class="get_cart_count"></span></button>
            </a>
            <form action="{% url 'logout' %}" method="post">
                {% csrf_token %}
                <button type="submit">Вийти</button>
            </form>
        {% endif %}
    </div>
</header>

<main>
    
    <h1 class="my_cabinet">Мій кабінет</h1>
    <p>Ласкаво просимо, <span id="user-first-name">{{ user.first_name }}</span> <span
            id="user-last-name">{{ user.last_name }}</span>!</p>
    <p>Вік: <span id="user-age">{{ user.age }}</span></p>
    <p>Мобільний: <span id="user-mobile">{{ user.mobile }}</span></p>
    <p>Адреса: <span id="user-address">{{ user.address }}</span></p>
    <p>Email: <span id="user-email">{{ user.email }}</span></p>

    <button id="edit-profile-btn" onclick="editProfile()">Редагувати</button>

    <form id="profile-form" method="post" style="display: none;">
        {% csrf_token %}
        <input type="text" name="first_name" id="first_name" value="{{ user.first_name }}" placeholder="Ім'я">
        <input type="text" name="last_name" id="last_name" value="{{ user.last_name }}" placeholder="Прізвище">
        <input type="text" name="age" id="age" value="{{ user.age }}" placeholder="Вік">
        <input type="text" name="mobile" id="mobile" value="{{ user.mobile }}" placeholder="Мобільний">
        <input type="text" name="address" id="address" value="{{ user.address }}" placeholder="Адреса">
        <input type="email" name="email" id="email" value="{{ user.email }}" placeholder="Email">
        <button type="submit" id="update-profile-btn" style="display: none;">Зберегти зміни</button>
    </form>
</main>
<footer>
    <div class="contact-info">
        <h3>Контактна інформація:</h3>
        <p>+380 99 444 45 67</p>
        <p>exam@mail.com</p>
    </div>
</footer>
</body>
</html>

templates/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Registration</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/register.css' %}">
</head>
<body>
<header>
    <div class="left-content">
        <a href="{% url 'home' %}">
            <img src="{% static 'images/apple_logo.png' %}" alt="Apple Logo">
        </a>
        <div class="dropdown" onmouseover="showiPhoneModels()" onmouseleave="hideiPhoneModels()">
            <a href="{% url 'iphone' %}">
                <button>
                    <i class="fas fa-mobile-alt"></i> iPhone
                </button>
            </a>
        </div>
    </div>
    <div class="right-content">
        {% if user.is_authenticated %}
            <a href="{% url 'profile' %}">
                <button><i class="fas fa-user"></i> {{ user.first_name }}</button>
            </a>
            <a href="{% url 'confirm_order' %}">
                <button><i class="fas fa-shopping-basket"></i><span class="get_cart_count"></span></button>
            </a>
            <form action="{% url 'logout' %}" method="post">
                {% csrf_token %}
                <button type="submit">Вийти</button>
            </form>
        {% else %}
            <a href="{% url 'login' %}">Вхід</a>
        {% endif %}
    </div>
</header>
<main>
    <div class="container">
        <h2>Реєстрація</h2>
        <form method="post" action="{% url 'register' %}">
            {% csrf_token %}
            <div class="form-group">
                <label for="id_first_name">Імʼя:</label><br>
                {{ form.first_name }}
            </div>
            <div class="form-group">
                <label for="id_age">Вік:</label><br>
                {{ form.age }}
            </div>
            <div class="form-group">
                <label for="id_email">Email:</label><br>
                {{ form.email }}
            </div>
            <div class="form-group">
                <label for="id_mobile">Телефон:</label><br>
                {{ form.mobile }}
            </div>
            <div class="form-group">
                <label for="id_address">Адреса:</label><br>
                {{ form.address }}
            </div>
            <div class="form-group">
                <label for="id_password">Пароль:</label><br>
                {{ form.password }}
            </div>
            <div class="form-group">
                <label for="id_confirm_password">Підтвердьте пароль:</label><br>
                {{ form.confirm_password }}
            </div>
            <button type="submit">Register</button>
        </form>
    </div>
</main>
<footer>
    <div class="contact-info">
        <h3>Контактна інформація:</h3>
        <p>+380 99 444 45 67</p>
        <p>exam@mail.com</p>
    </div>
</footer>
</body>
</html>